#pragma once
#include"appframe.h"
#include"modeGame.h"
#include"modeTitle.h"
#include"modeMenu.h"
#include"modeResult.h"
#include"modeGameOver.h"
#include"modeMainMenu.h"
#include"modeBossChoose.h"

#define MODE_GAME "game"
#define MODE_TITLE "title"
#define MODE_MENU "menu"
#define MODE_RESULT "result"
#define MODE_GO "gameOver"
#define MODE_MM "mainMenu"
#define MODE_BC "bossChoose"
