#pragma once
#include"appframe.h"
#include"modeGame.h"
#include"modeTitle.h"
#include"modeMenu.h"
#include"modeResult.h"
#include"modeGameOver.h"
#include"modeMainMenu.h"
#include"modeBossChoose.h"
#include"modeEquipmentSelection.h"
#include"modeSetting.h"
#include"modeArtsGet.h"
#include"modeEnd.h"

#define MODE_GAME "game"
#define MODE_TITLE "title"
#define MODE_MENU "menu"
#define MODE_RESULT "result"
#define MODE_GAMEOVER "gameOver"
#define MODE_MAINMENU "mainMenu"
#define MODE_BOSSCHOICE "bossChoose"
#define MODE_EQUIPMENTSELECTION "EquipmentSelection"
#define MODE_SETTING "setting"
#define MODE_ARTSGET "artsGet"
#define MODE_GAMEENDING "gameEnding"

#define Char_PL "player"
#define Char_BOSS1 "Boss1"
#define Char_BOSS2 "Boss2"
#define Char_LBOSS "LBoss"
#define Char_TARGET "target"
